version: '2'

networks:
    common:

services:
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
            # If you want to custom redis config, edit file in config folder and uncomment following line
            - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        #user: "${UID_GID}"
        user: "0:0"
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always

